### ISSUE TITLE
please help me......

### ISSUE THREAD

**Issue by lurchycc** [yuanming-hu/exposure#27]
D:\exposure-master\exposure-master>python train.py example test
Scripts are backed up. Initializing network...
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    main()
  File "train.py", line 13, in main
    net = GAN(cfg, restore=False)
  File "D:\exposure-master\exposure-master\net.py", line 44, in __init__
    self.memory = ReplayMemory(cfg, load=not restore)
  File "D:\exposure-master\exposure-master\replay_memory.py", line 12, in __init__
    self.real_dataset = cfg.real_data_provider()
  File "D:\exposure-master\exposure-master\config_example.py", line 198, in <lambda>
    set_name='2k_target')
  File "D:\exposure-master\exposure-master\artist.py", line 46, in __init__
    idx = list(map(int, idx))
ValueError: invalid literal for int() with base 10: '# Note: this list is 1-based, i.e. ids are among [1, 5000]\n'
D:\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

**Comment by yuanming-hu** [comment]
I think a quick solution is to run it on Linux...I have never tested the code on Windows.

**Comment by yuanming-hu** [comment]
Could you try the latest commit?

**Comment by lurchycc** [comment]
# File 3/3
Traceback (most recent call last):

  File "<ipython-input-1-50f60986d2db>", line 1, in <module>
    runfile('D:/exposure-master/exposure-master/fetch_fivek.py', wdir='D:/exposure-master/exposure-master')

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/exposure-master/exposure-master/fetch_fivek.py", line 55, in <module>
    download(fn_template.format('meta_raw.pkl'), path='data/fivek_dataset/sup_batched80aug_daylight')

  File "D:/exposure-master/exposure-master/fetch_fivek.py", line 16, in download
    u = urllib.request.urlopen(url)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 532, in open
    response = meth(req, response)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 544, in _open
    '_open', req)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)

  File "D:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)

URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by lurchycc** [comment]
然后就是刚才那种情况了，我在Linux上试试吧，thank you.
