### ISSUE TITLE
how to train it  in supervised version

### ISSUE THREAD

**Issue by sykxiaoqiang** [yuanming-hu/exposure#40]
When i change 'cfg.supervised' , it makes mistakes.
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    main()
  File "train.py", line 14, in main
    net.train()
  File "/home/syk/exposure/net.py", line 373, in train
    run_metadata=run_metadata)
  File "/home/syk/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/syk/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 64, 3) for Tensor 'fake_input:0', which has shape '(?, 64, 64, 3)'

**Comment by yuanming-hu** [comment]
I don't think the supervised version works anymore...

**Comment by KrisChou** [comment]
OK, i got it
