### ISSUE TITLE
Is there any chance to get this working in Win64?

### ISSUE THREAD

**Issue by FrankEscobar** [yuanming-hu/exposure#41]
I tried but I get an invalid syntax at util.py, line 658

Thank you in advance

**Comment by areslp** [comment]
I just comment the function `test_async_task_manager` and it runs...
But I met another problem:
```
Traceback (most recent call last):
  File "evaluate.py", line 35, in <module>
    evaluate()
  File "evaluate.py", line 31, in evaluate
    net.eval(spec_files=spec_files, step_by_step=True)
  File "D:\deep_learning\exposure\net.py", line 732, in eval
    image = read_tiff16(fn)
  File "D:\deep_learning\exposure\util.py", line 320, in read_tiff16
    img = tifffile.imread(fn)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tifffile\tifffile.py", line 719, in imread
    return imseq.asarray(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tifffile\tifffile.py", line 5947, in asarray
    func(index, fname)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tifffile\tifffile.py", line 5937, in func
    result[index] = im
ValueError: could not broadcast input array from shape (500,333,3) into shape (333,500,3)
```
Still trying...

**Comment by areslp** [comment]
I found the problem, it's because the wildcard is not working properly in windows' power shell...
I use the following command and it works.

`python evaluate.py example pretrained models/sample_inputs/A.tif models/sample_inputs/B.tif models/sample_inputs/C.tif models/sample_inputs/D.tif models/sample_inputs/E.tif models/sample_inputs/F.tif models/sample_inputs/G.tif models/sample_inputs/H.tif`
