### ISSUE TITLE
Error while importing Util

### ISSUE THREAD

**Issue by saikrishna232** [yuanming-hu/exposure#56]
(temp) C:\Users\IM-LP-1453\exposure>python evaluate.py example pretrained models/sample_inputs/*.tif
Traceback (most recent call last):
  File "evaluate.py", line 4, in <module>
    from net import GAN
  File "C:\Users\IM-LP-1453\exposure\net.py", line 1, in <module>
    from util import STATE_DROPOUT_BEGIN, STATE_REWARD_DIM, STATE_STEP_DIM, STATE_STOPPED_DIM
  File "C:\Users\IM-LP-1453\exposure\util.py", line 658
    async = AsyncTaskManager(task)
          ^
SyntaxError: invalid syntax

**Comment by nman76** [comment]
I got the same problem..

**Comment by hanjiacheng** [comment]
‘async’ is python reserved fields,rename it can work.

**Comment by seeyourcell** [comment]
信已收到，谢谢！我会尽快回复。                林焕
